### ISSUE TITLE
Racism is bad and nullpickle has a SMALL DICk

### ISSUE THREAD

**Issue by nullpixel1** [applebetasissupercool/Fucc#1]

**Comment by cyanisaac** [comment]
fucc you

**Comment by cyanisaac** [comment]
no

**Comment by AppleBetas** [comment]
ayy lit fam

**Comment by AppleBetas** [comment]
fuck

**Comment by AppleBetas** [comment]
die

**Comment by AppleBetas** [comment]
ass

**Comment by AppleBetas** [comment]
email sucks

**Comment by AppleBetas** [comment]
ol

**Comment by AppleBetas** [comment]
I don't think this has been resolved, he appears to still be a cock. Reopening.

**Comment by cyanisaac** [comment]
putting it on record that it's 6:55 in the UK and he still hasn't resolved this issue.

**Comment by cyanisaac** [comment]
Issue not resolved, and new information has been discovered about the issue. I will be updating the issue in order to get us to a solution ASAP, since this affects production.

**Comment by cyanisaac** [comment]
let's get this moving 😠

**Comment by cyanisaac** [comment]
shit now our issue is racist

**Comment by AppleBetas** [comment]
Didn't see that coming
